import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const { isAuthenticated } = getKindeServerSession();
    const authenticated = await isAuthenticated();
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Header title={metadata.title} isAuthenticated={authenticated}/>
        <section className="pt-16">
        {children}
        </section>
        <Footer/>
      </body>
    </html>
  );
}
