import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";


export const metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Header title={metadata.title}/>
        <section className="pt-16">
        {children}
        </section>
        <Footer/>
      </body>
    </html>
  );
}
