import { notFound } from "next/navigation";

export const metadata = {
  title: "Blog Details | First Next App",
  description: "Generated by create next app",
};

const SingleBlog = async ({ params }) => {
  const { id } = await params;
  if (id === "3") {
    notFound();
  }
  return (
    <div>
      <h1 className="text-5xl my-2 text-center">Dynamic Route</h1>
      SingleBlog id is {id}
    </div>
  );
};

export default SingleBlog;
